### ISSUE TITLE
Getting error invalid character 'u' looking for beginning of value

### ISSUE THREAD

**Issue by thejaimin** [codenze/bard-api-node#2]
const assistant = new BardAPI(); 
await assistant.setSession('__Secure-1PSID', '');
const response = await assistant.getBardResponse('Hello, how are you?');

<img width="678" alt="Screenshot 2023-10-02 at 9 37 19 PM" src="https://github.com/codenze/bard-api-node/assets/7807881/e25322e2-5ed9-41e9-9c73-e1ecb687c85e">

**Comment by nooufiy** [comment]
error:
Error: Pattern not found.

**Comment by codenze** [comment]
Thank you @thejaimin for reporting the issue! I appreciate your effort in bringing it to my attention.

The reported issue was indeed related to invalid authentication credentials. I have since made enhancements to the code, including improved error messages. These changes aim to provide more clarity to users encountering authentication and data retrieval issues and offer suggestions for resolution. I hope these improvements will be valuable to anyone facing similar errors in the future.

Your feedback was instrumental in making these improvements, and I'm grateful for your contribution to the project.
